export enum SortBy {
  MOST_EXPENSIVE_FIRST = "MOST_EXPENSIVE_FIRST",
  CHEAPEST_FIRST = "CHEAPEST_FIRST",
  NAME_A_Z = "NAME_A_Z",
  NAME_Z_A = "NAME_Z_A",
  NEWEST_FIRST = "NEWEST_FIRST",
  OLDEST_FIRST = "OLDEST_FIRST",
}
