version: "3.4"

services:
  bankoftime-frontend:
    container_name: bankoftime-frontend
    image: docker.io/marekkawalski/bankoftime-frontend:0.0.2
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  bankoftime-backend:
    container_name: bankoftime-backend
    image: docker.io/marekkawalski/bankoftime-backend:0.1.1
    build:
      context: ./backend/BankOfTime
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - bankoftime-db

  bankoftime-db:
    container_name: bankoftime-db
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
      MSSQL_SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
