version: "3.4"

services:
  bankoftime-frontend:
    container_name: bankoftime-frontend
    image: docker.io/marekkawalski/bankoftime-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  bankoftime-backend:
    container_name: bankoftime-backend
    image: docker.io/marekkawalski/bankoftime-backend:latest
    build:
      context: ./backend/BankOfTime
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:sqlserver://localhost:1433;Server=bankoftime-db;databaseName=BankOfTime;encrypt=true;trustServerCertificate=true;Integrated Security=false
    ports:
      - "8080:8080"
    depends_on:
      - bankoftime-db

  bankoftime-db:
    container_name: bankoftime-db
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      MSSQL_SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
