name: Backend Continues Delivery Workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"
      - "!**/*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/BankOfTime

    steps:
      - name: docker login
        uses: docker/login-action@1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build the docker image
        run: docker build --file Dockerfile --tag marekkawalski/bankoftime-backend:latest .
      - name: Docker Push
        run: docker push marekkawalski/bankoftime-backend:latest
