name: Backend Continues Delivery Workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"
      - "!**/*.md"
jobs:
  build:
    name: Build backend Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/BankOfTime
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build the docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bankoftime-backend:latest
